from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

import psycopg
from psycopg.rows import dict_row


@dataclass(frozen=True)
class RateLimitDecision:
    allowed: bool
    retry_after: int = 0


class RateLimitStore:
    """Small PostgreSQL-backed rolling-window limiter for public auth endpoints."""

    def __init__(self, database_url: str):
        self.conn = psycopg.connect(database_url, row_factory=dict_row)
        self._create_schema()

    def _create_schema(self) -> None:
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS auth_rate_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scope TEXT NOT NULL,
                key_hash CHAR(64) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        self.conn.execute(
            """
            CREATE INDEX IF NOT EXISTS auth_rate_events_lookup_idx
            ON auth_rate_events(scope, key_hash, created_at)
            """
        )
        self.conn.execute(
            "CREATE INDEX IF NOT EXISTS auth_rate_events_created_at_idx "
            "ON auth_rate_events(created_at)"
        )
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()

    @staticmethod
    def _key_hash(key: str) -> str:
        return hashlib.sha256(key.encode("utf-8")).hexdigest()

    def hit(self, scope: str, key: str, *, limit: int, window_seconds: int) -> RateLimitDecision:
        if limit < 1 or window_seconds < 1:
            raise ValueError("rate limit and window must be positive")

        key_hash = self._key_hash(key)
        cutoff = datetime.now(timezone.utc) - timedelta(seconds=window_seconds)

        # Serialize checks for one limiter key to keep concurrent requests from
        # racing the count/insert sequence.
        self.conn.execute(
            "SELECT pg_advisory_xact_lock(hashtext(%s), hashtext(%s))",
            (scope, key_hash),
        )
        row = self.conn.execute(
            """
            SELECT COUNT(*) AS n, MIN(created_at) AS oldest
            FROM auth_rate_events
            WHERE scope=%s AND key_hash=%s AND created_at >= %s
            """,
            (scope, key_hash, cutoff),
        ).fetchone()

        count = int(row["n"])
        if count >= limit:
            oldest = row["oldest"]
            remaining = (oldest + timedelta(seconds=window_seconds) - datetime.now(timezone.utc)).total_seconds()
            self.conn.commit()
            return RateLimitDecision(False, max(1, math.ceil(remaining)))

        self.conn.execute(
            "INSERT INTO auth_rate_events(scope,key_hash) VALUES (%s,%s)",
            (scope, key_hash),
        )
        self.conn.commit()
        return RateLimitDecision(True)

    def clear(self, scope: str, key: str) -> None:
        self.conn.execute(
            "DELETE FROM auth_rate_events WHERE scope=%s AND key_hash=%s",
            (scope, self._key_hash(key)),
        )
        self.conn.commit()

    def cleanup(self, *, older_than_hours: int = 24) -> int:
        cursor = self.conn.execute(
            "DELETE FROM auth_rate_events WHERE created_at < now() - (%s * interval '1 hour')",
            (older_than_hours,),
        )
        self.conn.commit()
        return cursor.rowcount
