from __future__ import annotations

from dataclasses import dataclass

import psycopg
from psycopg.errors import UniqueViolation
from psycopg.rows import dict_row

VALID_STATUSES = ("planned", "learning", "learned", "later")
VALID_REASONS = ("need", "revisit", "curious")


@dataclass(frozen=True)
class Topic:
    id: int
    name: str
    url: str | None
    status: str


@dataclass(frozen=True)
class Encounter:
    context: Topic
    topic: Topic
    reason: str
    note: str


@dataclass(frozen=True)
class TopicSummary:
    topic: Topic
    came_up_in_count: int
    flagged_count: int

    @property
    def isolated(self) -> bool:
        return self.came_up_in_count == 0 and self.flagged_count == 0


@dataclass(frozen=True)
class User:
    id: int
    email: str
    password_hash: str
    active: bool


class StoreError(Exception):
    pass


class TopicNotFound(StoreError):
    pass


class DuplicateTopic(StoreError):
    pass


class InvalidEncounter(StoreError):
    pass


class UserNotFound(StoreError):
    pass


class DuplicateUser(StoreError):
    pass


class Store:
    def __init__(self, database_url: str, *, user_id: int | None = None):
        self.database_url = database_url
        self.user_id = user_id
        self.conn = psycopg.connect(database_url, row_factory=dict_row)
        self._create_schema()

    def _column_exists(self, table: str, column: str) -> bool:
        row = self.conn.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema=current_schema() AND table_name=%s AND column_name=%s
            """,
            (table, column),
        ).fetchone()
        return row is not None

    def _migration_user_id(self) -> int:
        import os

        email = os.environ.get("LEARNING_LINKS_MIGRATION_USER")
        if email:
            return self.get_user(email).id
        rows = self.conn.execute(
            "SELECT id FROM users WHERE active=TRUE ORDER BY id"
        ).fetchall()
        if len(rows) == 1:
            return int(rows[0]["id"])
        if not rows:
            raise StoreError(
                "existing workspace needs an owner; create a user first or set LEARNING_LINKS_MIGRATION_USER"
            )
        raise StoreError(
            "existing workspace owner is ambiguous; set LEARNING_LINKS_MIGRATION_USER to an existing user email"
        )

    def _create_schema(self) -> None:
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_unique ON users (lower(email))"
        )
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS topics (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                url TEXT,
                status TEXT NOT NULL DEFAULT 'planned'
                    CHECK(status IN ('planned','learning','learned','later'))
            )
            """
        )
        if not self._column_exists("topics", "user_id"):
            self.conn.execute(
                "ALTER TABLE topics ADD COLUMN user_id BIGINT REFERENCES users(id) ON DELETE CASCADE"
            )
        unowned_topics = int(
            self.conn.execute("SELECT COUNT(*) AS n FROM topics WHERE user_id IS NULL").fetchone()["n"]
        )
        if unowned_topics:
            owner_id = self._migration_user_id()
            self.conn.execute("UPDATE topics SET user_id=%s WHERE user_id IS NULL", (owner_id,))
        self.conn.execute("ALTER TABLE topics ALTER COLUMN user_id SET NOT NULL")
        self.conn.execute("DROP INDEX IF EXISTS topics_name_ci_unique")
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS topics_user_name_ci_unique ON topics (user_id, lower(name))"
        )
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS topics_user_id_id_unique ON topics (user_id, id)"
        )

        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS encounters (
                user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                context_topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                reason TEXT NOT NULL DEFAULT 'need'
                    CONSTRAINT encounters_reason_check
                    CHECK(reason IN ('need','revisit','curious')),
                note TEXT NOT NULL DEFAULT '',
                PRIMARY KEY(context_topic_id, topic_id),
                CHECK(context_topic_id <> topic_id)
            )
            """
        )
        if not self._column_exists("encounters", "user_id"):
            self.conn.execute(
                "ALTER TABLE encounters ADD COLUMN user_id BIGINT REFERENCES users(id) ON DELETE CASCADE"
            )
        self.conn.execute(
            """
            UPDATE encounters e
            SET user_id=t.user_id
            FROM topics t
            WHERE e.user_id IS NULL AND t.id=e.context_topic_id
            """
        )
        self.conn.execute("ALTER TABLE encounters ALTER COLUMN user_id SET NOT NULL")
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS encounters_user_pair_unique "
            "ON encounters (user_id, context_topic_id, topic_id)"
        )
        self.conn.execute(
            """
            DO $$ BEGIN
                ALTER TABLE encounters ADD CONSTRAINT encounters_context_owner_fk
                FOREIGN KEY(user_id, context_topic_id)
                REFERENCES topics(user_id, id) ON DELETE CASCADE;
            EXCEPTION WHEN duplicate_object THEN NULL; END $$
            """
        )
        self.conn.execute(
            """
            DO $$ BEGIN
                ALTER TABLE encounters ADD CONSTRAINT encounters_topic_owner_fk
                FOREIGN KEY(user_id, topic_id)
                REFERENCES topics(user_id, id) ON DELETE CASCADE;
            EXCEPTION WHEN duplicate_object THEN NULL; END $$
            """
        )
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()

    def _workspace_user_id(self) -> int:
        if self.user_id is None:
            raise StoreError("workspace operations require a user")
        return self.user_id

    @staticmethod
    def _topic(row) -> Topic:
        return Topic(row["id"], row["name"], row["url"], row["status"])

    @staticmethod
    def _user(row) -> User:
        return User(row["id"], row["email"], row["password_hash"], row["active"])

    def ping(self) -> None:
        self.conn.execute("SELECT 1").fetchone()

    def get_topic(self, name: str) -> Topic:
        user_id = self._workspace_user_id()
        row = self.conn.execute(
            """
            SELECT id,name,url,status
            FROM topics
            WHERE user_id=%s AND lower(name)=lower(%s)
            """,
            (user_id, name),
        ).fetchone()
        if row is None:
            raise TopicNotFound(f"topic not found: {name}")
        return self._topic(row)

    def add_topic(self, name: str, url: str | None = None, status: str = "planned") -> Topic:
        user_id = self._workspace_user_id()
        name = name.strip()
        if not name:
            raise StoreError("topic name cannot be empty")
        if status not in VALID_STATUSES:
            raise StoreError(f"invalid status: {status}")
        try:
            self.conn.execute(
                "INSERT INTO topics(user_id,name,url,status) VALUES (%s,%s,%s,%s)",
                (user_id, name, url, status),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateTopic(f"topic already exists: {name}") from exc
        return self.get_topic(name)

    def list_topics(self) -> list[Topic]:
        user_id = self._workspace_user_id()
        rows = self.conn.execute(
            """
            SELECT id,name,url,status
            FROM topics
            WHERE user_id=%s
            ORDER BY lower(name)
            """,
            (user_id,),
        ).fetchall()
        return [self._topic(row) for row in rows]

    def edit_topic(self, name: str, *, new_name=None, url=None, status=None, set_url=False) -> Topic:
        user_id = self._workspace_user_id()
        topic = self.get_topic(name)
        final_name = new_name.strip() if new_name is not None else topic.name
        final_url = url if set_url else topic.url
        final_status = status if status is not None else topic.status

        if not final_name:
            raise StoreError("topic name cannot be empty")
        if final_status not in VALID_STATUSES:
            raise StoreError(f"invalid status: {final_status}")

        try:
            self.conn.execute(
                """
                UPDATE topics
                SET name=%s, url=%s, status=%s
                WHERE user_id=%s AND id=%s
                """,
                (final_name, final_url, final_status, user_id, topic.id),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateTopic(f"topic already exists: {final_name}") from exc
        return self.get_topic(final_name)

    def remove_topic(self, name: str) -> None:
        user_id = self._workspace_user_id()
        topic = self.get_topic(name)
        self.conn.execute(
            "DELETE FROM topics WHERE user_id=%s AND id=%s",
            (user_id, topic.id),
        )
        self.conn.commit()

    def flag(self, context_name: str, topic_name: str, reason: str = "need", note: str = "") -> Encounter:
        user_id = self._workspace_user_id()
        if reason not in VALID_REASONS:
            raise InvalidEncounter(f"invalid encounter reason: {reason}")

        context = self.get_topic(context_name)
        topic = self.get_topic(topic_name)
        if context.id == topic.id:
            raise InvalidEncounter("a topic cannot be flagged from itself")

        note = note.strip()
        self.conn.execute(
            """
            INSERT INTO encounters(user_id,context_topic_id,topic_id,reason,note)
            VALUES (%s,%s,%s,%s,%s)
            ON CONFLICT(user_id,context_topic_id,topic_id)
            DO UPDATE SET reason=excluded.reason,note=excluded.note
            """,
            (user_id, context.id, topic.id, reason, note),
        )
        self.conn.commit()
        return Encounter(context, topic, reason, note)

    def unflag(self, context_name: str, topic_name: str) -> bool:
        user_id = self._workspace_user_id()
        context = self.get_topic(context_name)
        topic = self.get_topic(topic_name)
        cursor = self.conn.execute(
            """
            DELETE FROM encounters
            WHERE user_id=%s AND context_topic_id=%s AND topic_id=%s
            """,
            (user_id, context.id, topic.id),
        )
        self.conn.commit()
        return cursor.rowcount > 0

    def came_up_in(self, name: str) -> list[tuple[Topic, str, str]]:
        user_id = self._workspace_user_id()
        topic = self.get_topic(name)
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,e.reason,e.note
            FROM encounters e
            JOIN topics t ON t.user_id=e.user_id AND t.id=e.context_topic_id
            WHERE e.user_id=%s AND e.topic_id=%s
            ORDER BY lower(t.name)
            """,
            (user_id, topic.id),
        ).fetchall()
        return [(self._topic(row), row["reason"], row["note"]) for row in rows]

    def flagged_from(self, name: str) -> list[tuple[Topic, str, str]]:
        user_id = self._workspace_user_id()
        context = self.get_topic(name)
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,e.reason,e.note
            FROM encounters e
            JOIN topics t ON t.user_id=e.user_id AND t.id=e.topic_id
            WHERE e.user_id=%s AND e.context_topic_id=%s
            ORDER BY lower(t.name)
            """,
            (user_id, context.id),
        ).fetchall()
        return [(self._topic(row), row["reason"], row["note"]) for row in rows]

    def recurring_topics(self) -> list[tuple[Topic, int]]:
        user_id = self._workspace_user_id()
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,COUNT(e.context_topic_id) AS n
            FROM topics t
            LEFT JOIN encounters e ON e.user_id=t.user_id AND e.topic_id=t.id
            WHERE t.user_id=%s
            GROUP BY t.id
            ORDER BY n DESC,lower(t.name)
            """,
            (user_id,),
        ).fetchall()
        return [(self._topic(row), int(row["n"])) for row in rows]

    def overview(self) -> list[TopicSummary]:
        user_id = self._workspace_user_id()
        rows = self.conn.execute(
            """
            SELECT
                t.id,t.name,t.url,t.status,
                (SELECT COUNT(*) FROM encounters e
                 WHERE e.user_id=t.user_id AND e.topic_id=t.id) AS came_up_in_count,
                (SELECT COUNT(*) FROM encounters e
                 WHERE e.user_id=t.user_id AND e.context_topic_id=t.id) AS flagged_count
            FROM topics t
            WHERE t.user_id=%s
            ORDER BY lower(t.name)
            """,
            (user_id,),
        ).fetchall()
        return [
            TopicSummary(
                topic=self._topic(row),
                came_up_in_count=int(row["came_up_in_count"]),
                flagged_count=int(row["flagged_count"]),
            )
            for row in rows
        ]

    def isolated_topics(self) -> list[Topic]:
        return [summary.topic for summary in self.overview() if summary.isolated]

    def counts(self) -> tuple[int, int]:
        user_id = self._workspace_user_id()
        topics = int(
            self.conn.execute(
                "SELECT COUNT(*) AS n FROM topics WHERE user_id=%s",
                (user_id,),
            ).fetchone()["n"]
        )
        encounters = int(
            self.conn.execute(
                "SELECT COUNT(*) AS n FROM encounters WHERE user_id=%s",
                (user_id,),
            ).fetchone()["n"]
        )
        return topics, encounters

    def reset(self) -> tuple[int, int]:
        user_id = self._workspace_user_id()
        counts = self.counts()
        self.conn.execute("DELETE FROM topics WHERE user_id=%s", (user_id,))
        self.conn.commit()
        return counts

    def encounters(self) -> list[Encounter]:
        user_id = self._workspace_user_id()
        rows = self.conn.execute(
            """
            SELECT e.reason,e.note,
                   c.id AS c_id,c.name AS c_name,c.url AS c_url,c.status AS c_status,
                   t.id AS t_id,t.name AS t_name,t.url AS t_url,t.status AS t_status
            FROM encounters e
            JOIN topics c ON c.user_id=e.user_id AND c.id=e.context_topic_id
            JOIN topics t ON t.user_id=e.user_id AND t.id=e.topic_id
            WHERE e.user_id=%s
            ORDER BY lower(c.name),lower(t.name)
            """,
            (user_id,),
        ).fetchall()
        return [
            Encounter(
                Topic(row["c_id"], row["c_name"], row["c_url"], row["c_status"]),
                Topic(row["t_id"], row["t_name"], row["t_url"], row["t_status"]),
                row["reason"],
                row["note"],
            )
            for row in rows
        ]

    def add_user(self, email: str, password_hash: str) -> User:
        email = email.strip().lower()
        if not email:
            raise StoreError("email cannot be empty")
        try:
            self.conn.execute(
                "INSERT INTO users(email,password_hash) VALUES (%s,%s)",
                (email, password_hash),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateUser(f"user already exists: {email}") from exc
        return self.get_user(email)

    def get_user(self, email: str) -> User:
        row = self.conn.execute(
            "SELECT id,email,password_hash,active FROM users WHERE lower(email)=lower(%s)",
            (email,),
        ).fetchone()
        if row is None:
            raise UserNotFound(f"user not found: {email}")
        return self._user(row)

    def list_users(self) -> list[User]:
        rows = self.conn.execute(
            "SELECT id,email,password_hash,active FROM users ORDER BY lower(email)"
        ).fetchall()
        return [self._user(row) for row in rows]

    def set_user_active(self, email: str, active: bool) -> User:
        cursor = self.conn.execute(
            "UPDATE users SET active=%s WHERE lower(email)=lower(%s)",
            (active, email),
        )
        if cursor.rowcount == 0:
            self.conn.rollback()
            raise UserNotFound(f"user not found: {email}")
        self.conn.commit()
        return self.get_user(email)

    def set_user_password(self, email: str, password_hash: str) -> User:
        cursor = self.conn.execute(
            "UPDATE users SET password_hash=%s WHERE lower(email)=lower(%s)",
            (password_hash, email),
        )
        if cursor.rowcount == 0:
            self.conn.rollback()
            raise UserNotFound(f"user not found: {email}")
        self.conn.commit()
        return self.get_user(email)
