from __future__ import annotations

from dataclasses import dataclass

import psycopg
from psycopg.errors import UniqueViolation
from psycopg.rows import dict_row

VALID_STATUSES = ("planned", "learning", "learned", "later")
VALID_REASONS = ("need", "revisit", "curious")


@dataclass(frozen=True)
class Topic:
    id: int
    name: str
    url: str | None
    status: str


@dataclass(frozen=True)
class Encounter:
    context: Topic
    topic: Topic
    reason: str
    note: str


@dataclass(frozen=True)
class TopicSummary:
    topic: Topic
    came_up_in_count: int
    flagged_count: int

    @property
    def isolated(self) -> bool:
        return self.came_up_in_count == 0 and self.flagged_count == 0


@dataclass(frozen=True)
class User:
    id: int
    email: str
    password_hash: str
    active: bool


class StoreError(Exception):
    pass


class TopicNotFound(StoreError):
    pass


class DuplicateTopic(StoreError):
    pass


class InvalidEncounter(StoreError):
    pass


class UserNotFound(StoreError):
    pass


class DuplicateUser(StoreError):
    pass


class Store:
    def __init__(self, database_url: str):
        self.database_url = database_url
        self.conn = psycopg.connect(database_url, row_factory=dict_row)
        self._create_schema()

    def _create_schema(self) -> None:
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS topics (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                url TEXT,
                status TEXT NOT NULL DEFAULT 'planned'
                    CHECK(status IN ('planned','learning','learned','later'))
            )
            """
        )
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS topics_name_ci_unique ON topics (lower(name))"
        )
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS encounters (
                context_topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                reason TEXT NOT NULL DEFAULT 'need'
                    CONSTRAINT encounters_reason_check
                    CHECK(reason IN ('need','revisit','curious')),
                note TEXT NOT NULL DEFAULT '',
                PRIMARY KEY(context_topic_id, topic_id),
                CHECK(context_topic_id <> topic_id)
            )
            """
        )
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_unique ON users (lower(email))"
        )
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()

    @staticmethod
    def _topic(row) -> Topic:
        return Topic(row["id"], row["name"], row["url"], row["status"])

    @staticmethod
    def _user(row) -> User:
        return User(row["id"], row["email"], row["password_hash"], row["active"])

    def ping(self) -> None:
        self.conn.execute("SELECT 1").fetchone()

    def get_topic(self, name: str) -> Topic:
        row = self.conn.execute(
            "SELECT id,name,url,status FROM topics WHERE lower(name)=lower(%s)",
            (name,),
        ).fetchone()
        if row is None:
            raise TopicNotFound(f"topic not found: {name}")
        return self._topic(row)

    def add_topic(self, name: str, url: str | None = None, status: str = "planned") -> Topic:
        name = name.strip()
        if not name:
            raise StoreError("topic name cannot be empty")
        if status not in VALID_STATUSES:
            raise StoreError(f"invalid status: {status}")
        try:
            self.conn.execute(
                "INSERT INTO topics(name,url,status) VALUES (%s,%s,%s)",
                (name, url, status),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateTopic(f"topic already exists: {name}") from exc
        return self.get_topic(name)

    def list_topics(self) -> list[Topic]:
        rows = self.conn.execute(
            "SELECT id,name,url,status FROM topics ORDER BY lower(name)"
        ).fetchall()
        return [self._topic(row) for row in rows]

    def edit_topic(self, name: str, *, new_name=None, url=None, status=None, set_url=False) -> Topic:
        topic = self.get_topic(name)
        final_name = new_name.strip() if new_name is not None else topic.name
        final_url = url if set_url else topic.url
        final_status = status if status is not None else topic.status

        if not final_name:
            raise StoreError("topic name cannot be empty")
        if final_status not in VALID_STATUSES:
            raise StoreError(f"invalid status: {final_status}")

        try:
            self.conn.execute(
                "UPDATE topics SET name=%s, url=%s, status=%s WHERE id=%s",
                (final_name, final_url, final_status, topic.id),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateTopic(f"topic already exists: {final_name}") from exc
        return self.get_topic(final_name)

    def remove_topic(self, name: str) -> None:
        topic = self.get_topic(name)
        self.conn.execute("DELETE FROM topics WHERE id=%s", (topic.id,))
        self.conn.commit()

    def flag(self, context_name: str, topic_name: str, reason: str = "need", note: str = "") -> Encounter:
        if reason not in VALID_REASONS:
            raise InvalidEncounter(f"invalid encounter reason: {reason}")

        context = self.get_topic(context_name)
        topic = self.get_topic(topic_name)
        if context.id == topic.id:
            raise InvalidEncounter("a topic cannot be flagged from itself")

        note = note.strip()
        self.conn.execute(
            """
            INSERT INTO encounters(context_topic_id,topic_id,reason,note)
            VALUES (%s,%s,%s,%s)
            ON CONFLICT(context_topic_id,topic_id)
            DO UPDATE SET reason=excluded.reason,note=excluded.note
            """,
            (context.id, topic.id, reason, note),
        )
        self.conn.commit()
        return Encounter(context, topic, reason, note)

    def unflag(self, context_name: str, topic_name: str) -> bool:
        context = self.get_topic(context_name)
        topic = self.get_topic(topic_name)
        cursor = self.conn.execute(
            "DELETE FROM encounters WHERE context_topic_id=%s AND topic_id=%s",
            (context.id, topic.id),
        )
        self.conn.commit()
        return cursor.rowcount > 0

    def came_up_in(self, name: str) -> list[tuple[Topic, str, str]]:
        topic = self.get_topic(name)
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,e.reason,e.note
            FROM encounters e
            JOIN topics t ON t.id=e.context_topic_id
            WHERE e.topic_id=%s
            ORDER BY lower(t.name)
            """,
            (topic.id,),
        ).fetchall()
        return [(self._topic(row), row["reason"], row["note"]) for row in rows]

    def flagged_from(self, name: str) -> list[tuple[Topic, str, str]]:
        context = self.get_topic(name)
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,e.reason,e.note
            FROM encounters e
            JOIN topics t ON t.id=e.topic_id
            WHERE e.context_topic_id=%s
            ORDER BY lower(t.name)
            """,
            (context.id,),
        ).fetchall()
        return [(self._topic(row), row["reason"], row["note"]) for row in rows]

    def recurring_topics(self) -> list[tuple[Topic, int]]:
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,COUNT(e.context_topic_id) AS n
            FROM topics t
            LEFT JOIN encounters e ON e.topic_id=t.id
            GROUP BY t.id
            ORDER BY n DESC,lower(t.name)
            """
        ).fetchall()
        return [(self._topic(row), int(row["n"])) for row in rows]

    def overview(self) -> list[TopicSummary]:
        rows = self.conn.execute(
            """
            SELECT
                t.id,t.name,t.url,t.status,
                (SELECT COUNT(*) FROM encounters e WHERE e.topic_id=t.id) AS came_up_in_count,
                (SELECT COUNT(*) FROM encounters e WHERE e.context_topic_id=t.id) AS flagged_count
            FROM topics t
            ORDER BY lower(t.name)
            """
        ).fetchall()
        return [
            TopicSummary(
                topic=self._topic(row),
                came_up_in_count=int(row["came_up_in_count"]),
                flagged_count=int(row["flagged_count"]),
            )
            for row in rows
        ]

    def isolated_topics(self) -> list[Topic]:
        return [summary.topic for summary in self.overview() if summary.isolated]

    def counts(self) -> tuple[int, int]:
        topics = int(self.conn.execute("SELECT COUNT(*) AS n FROM topics").fetchone()["n"])
        encounters = int(self.conn.execute("SELECT COUNT(*) AS n FROM encounters").fetchone()["n"])
        return topics, encounters

    def reset(self) -> tuple[int, int]:
        counts = self.counts()
        self.conn.execute("DELETE FROM topics")
        self.conn.commit()
        return counts

    def encounters(self) -> list[Encounter]:
        rows = self.conn.execute(
            """
            SELECT e.reason,e.note,
                   c.id AS c_id,c.name AS c_name,c.url AS c_url,c.status AS c_status,
                   t.id AS t_id,t.name AS t_name,t.url AS t_url,t.status AS t_status
            FROM encounters e
            JOIN topics c ON c.id=e.context_topic_id
            JOIN topics t ON t.id=e.topic_id
            ORDER BY lower(c.name),lower(t.name)
            """
        ).fetchall()
        return [
            Encounter(
                Topic(row["c_id"], row["c_name"], row["c_url"], row["c_status"]),
                Topic(row["t_id"], row["t_name"], row["t_url"], row["t_status"]),
                row["reason"],
                row["note"],
            )
            for row in rows
        ]

    def add_user(self, email: str, password_hash: str) -> User:
        email = email.strip().lower()
        if not email:
            raise StoreError("email cannot be empty")
        try:
            self.conn.execute(
                "INSERT INTO users(email,password_hash) VALUES (%s,%s)",
                (email, password_hash),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateUser(f"user already exists: {email}") from exc
        return self.get_user(email)

    def get_user(self, email: str) -> User:
        row = self.conn.execute(
            "SELECT id,email,password_hash,active FROM users WHERE lower(email)=lower(%s)",
            (email,),
        ).fetchone()
        if row is None:
            raise UserNotFound(f"user not found: {email}")
        return self._user(row)

    def list_users(self) -> list[User]:
        rows = self.conn.execute(
            "SELECT id,email,password_hash,active FROM users ORDER BY lower(email)"
        ).fetchall()
        return [self._user(row) for row in rows]

    def set_user_active(self, email: str, active: bool) -> User:
        cursor = self.conn.execute(
            "UPDATE users SET active=%s WHERE lower(email)=lower(%s)",
            (active, email),
        )
        if cursor.rowcount == 0:
            self.conn.rollback()
            raise UserNotFound(f"user not found: {email}")
        self.conn.commit()
        return self.get_user(email)

    def set_user_password(self, email: str, password_hash: str) -> User:
        cursor = self.conn.execute(
            "UPDATE users SET password_hash=%s WHERE lower(email)=lower(%s)",
            (password_hash, email),
        )
        if cursor.rowcount == 0:
            self.conn.rollback()
            raise UserNotFound(f"user not found: {email}")
        self.conn.commit()
        return self.get_user(email)
