from __future__ import annotations

from dataclasses import dataclass

import psycopg
from psycopg.errors import UniqueViolation
from psycopg.rows import dict_row

VALID_STATUSES = ("planned", "learning", "learned", "later")
VALID_KINDS = ("prerequisite", "helpful", "related")


@dataclass(frozen=True)
class Topic:
    id: int
    name: str
    url: str | None
    status: str


@dataclass(frozen=True)
class Relationship:
    topic: Topic
    supporting_topic: Topic
    kind: str


@dataclass(frozen=True)
class TopicSummary:
    topic: Topic
    supported_by_count: int
    supports_count: int

    @property
    def isolated(self) -> bool:
        return self.supported_by_count == 0 and self.supports_count == 0


@dataclass(frozen=True)
class User:
    id: int
    email: str
    password_hash: str
    active: bool


class StoreError(Exception):
    pass


class TopicNotFound(StoreError):
    pass


class DuplicateTopic(StoreError):
    pass


class InvalidRelationship(StoreError):
    pass


class UserNotFound(StoreError):
    pass


class DuplicateUser(StoreError):
    pass


class Store:
    def __init__(self, database_url: str):
        self.database_url = database_url
        self.conn = psycopg.connect(database_url, row_factory=dict_row)
        self._create_schema()

    def _create_schema(self) -> None:
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS topics (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                url TEXT,
                status TEXT NOT NULL DEFAULT 'planned'
                    CHECK(status IN ('planned','learning','learned','later'))
            )
            """
        )
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS topics_name_ci_unique ON topics (lower(name))"
        )
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS relationships (
                topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                supporting_topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                kind TEXT NOT NULL CONSTRAINT relationships_kind_check
                    CHECK(kind IN ('prerequisite','helpful','related')),
                PRIMARY KEY(topic_id, supporting_topic_id),
                CHECK(topic_id <> supporting_topic_id)
            )
            """
        )
        relationship_kind_check = self.conn.execute(
            """
            SELECT pg_get_constraintdef(oid) AS definition
            FROM pg_constraint
            WHERE conrelid = 'relationships'::regclass
              AND conname = 'relationships_kind_check'
            """
        ).fetchone()
        if (
            relationship_kind_check
            and "'related'" not in relationship_kind_check["definition"]
        ):
            self.conn.execute(
                "ALTER TABLE relationships DROP CONSTRAINT relationships_kind_check"
            )
            self.conn.execute(
                """
                ALTER TABLE relationships
                ADD CONSTRAINT relationships_kind_check
                CHECK(kind IN ('prerequisite','helpful','related'))
                """
            )
        self.conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        self.conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_unique ON users (lower(email))"
        )
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()

    @staticmethod
    def _topic(row) -> Topic:
        return Topic(row["id"], row["name"], row["url"], row["status"])

    @staticmethod
    def _user(row) -> User:
        return User(row["id"], row["email"], row["password_hash"], row["active"])

    def ping(self) -> None:
        self.conn.execute("SELECT 1").fetchone()

    def get_topic(self, name: str) -> Topic:
        row = self.conn.execute(
            "SELECT id,name,url,status FROM topics WHERE lower(name)=lower(%s)",
            (name,),
        ).fetchone()
        if row is None:
            raise TopicNotFound(f"topic not found: {name}")
        return self._topic(row)

    def add_topic(self, name: str, url: str | None = None, status: str = "planned") -> Topic:
        name = name.strip()
        if not name:
            raise StoreError("topic name cannot be empty")
        if status not in VALID_STATUSES:
            raise StoreError(f"invalid status: {status}")
        try:
            self.conn.execute(
                "INSERT INTO topics(name,url,status) VALUES (%s,%s,%s)",
                (name, url, status),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateTopic(f"topic already exists: {name}") from exc
        return self.get_topic(name)

    def list_topics(self) -> list[Topic]:
        rows = self.conn.execute(
            "SELECT id,name,url,status FROM topics ORDER BY lower(name)"
        ).fetchall()
        return [self._topic(row) for row in rows]

    def edit_topic(self, name: str, *, new_name=None, url=None, status=None, set_url=False) -> Topic:
        topic = self.get_topic(name)
        final_name = new_name.strip() if new_name is not None else topic.name
        final_url = url if set_url else topic.url
        final_status = status if status is not None else topic.status

        if not final_name:
            raise StoreError("topic name cannot be empty")
        if final_status not in VALID_STATUSES:
            raise StoreError(f"invalid status: {final_status}")

        try:
            self.conn.execute(
                "UPDATE topics SET name=%s, url=%s, status=%s WHERE id=%s",
                (final_name, final_url, final_status, topic.id),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateTopic(f"topic already exists: {final_name}") from exc
        return self.get_topic(final_name)

    def remove_topic(self, name: str) -> None:
        topic = self.get_topic(name)
        self.conn.execute("DELETE FROM topics WHERE id=%s", (topic.id,))
        self.conn.commit()

    def link(self, topic_name: str, supporting_name: str, kind: str) -> Relationship:
        if kind not in VALID_KINDS:
            raise InvalidRelationship(f"invalid relationship kind: {kind}")

        topic = self.get_topic(topic_name)
        supporting = self.get_topic(supporting_name)
        if topic.id == supporting.id:
            raise InvalidRelationship("a topic cannot support itself")

        self.conn.execute(
            """
            INSERT INTO relationships(topic_id,supporting_topic_id,kind)
            VALUES (%s,%s,%s)
            ON CONFLICT(topic_id,supporting_topic_id)
            DO UPDATE SET kind=excluded.kind
            """,
            (topic.id, supporting.id, kind),
        )
        self.conn.commit()
        return Relationship(topic, supporting, kind)

    def unlink(self, topic_name: str, supporting_name: str) -> bool:
        topic = self.get_topic(topic_name)
        supporting = self.get_topic(supporting_name)
        cursor = self.conn.execute(
            "DELETE FROM relationships WHERE topic_id=%s AND supporting_topic_id=%s",
            (topic.id, supporting.id),
        )
        self.conn.commit()
        return cursor.rowcount > 0

    def supported_by(self, name: str):
        topic = self.get_topic(name)
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,r.kind
            FROM relationships r
            JOIN topics t ON t.id=r.supporting_topic_id
            WHERE r.topic_id=%s
            ORDER BY r.kind,lower(t.name)
            """,
            (topic.id,),
        ).fetchall()
        return [(self._topic(row), row["kind"]) for row in rows]

    def supports(self, name: str):
        topic = self.get_topic(name)
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,r.kind
            FROM relationships r
            JOIN topics t ON t.id=r.topic_id
            WHERE r.supporting_topic_id=%s
            ORDER BY r.kind,lower(t.name)
            """,
            (topic.id,),
        ).fetchall()
        return [(self._topic(row), row["kind"]) for row in rows]

    def importance(self):
        rows = self.conn.execute(
            """
            SELECT t.id,t.name,t.url,t.status,COUNT(r.topic_id) AS n
            FROM topics t
            LEFT JOIN relationships r ON r.supporting_topic_id=t.id
            GROUP BY t.id
            ORDER BY n DESC,lower(t.name)
            """
        ).fetchall()
        return [(self._topic(row), int(row["n"])) for row in rows]

    def overview(self) -> list[TopicSummary]:
        rows = self.conn.execute(
            """
            SELECT
                t.id,t.name,t.url,t.status,
                (SELECT COUNT(*) FROM relationships r WHERE r.topic_id=t.id) AS supported_by_count,
                (SELECT COUNT(*) FROM relationships r WHERE r.supporting_topic_id=t.id) AS supports_count
            FROM topics t
            ORDER BY lower(t.name)
            """
        ).fetchall()
        return [
            TopicSummary(
                topic=self._topic(row),
                supported_by_count=int(row["supported_by_count"]),
                supports_count=int(row["supports_count"]),
            )
            for row in rows
        ]

    def isolated_topics(self) -> list[Topic]:
        return [summary.topic for summary in self.overview() if summary.isolated]

    def counts(self) -> tuple[int, int]:
        topics = int(self.conn.execute("SELECT COUNT(*) AS n FROM topics").fetchone()["n"])
        relationships = int(
            self.conn.execute("SELECT COUNT(*) AS n FROM relationships").fetchone()["n"]
        )
        return topics, relationships

    def reset(self) -> tuple[int, int]:
        counts = self.counts()
        self.conn.execute("DELETE FROM topics")
        self.conn.commit()
        return counts

    def relationships(self) -> list[Relationship]:
        rows = self.conn.execute(
            """
            SELECT r.kind,
                   d.id AS d_id,d.name AS d_name,d.url AS d_url,d.status AS d_status,
                   s.id AS s_id,s.name AS s_name,s.url AS s_url,s.status AS s_status
            FROM relationships r
            JOIN topics d ON d.id=r.topic_id
            JOIN topics s ON s.id=r.supporting_topic_id
            ORDER BY lower(s.name),lower(d.name)
            """
        ).fetchall()
        return [
            Relationship(
                Topic(row["d_id"], row["d_name"], row["d_url"], row["d_status"]),
                Topic(row["s_id"], row["s_name"], row["s_url"], row["s_status"]),
                row["kind"],
            )
            for row in rows
        ]

    def add_user(self, email: str, password_hash: str) -> User:
        email = email.strip().lower()
        if not email:
            raise StoreError("email cannot be empty")
        try:
            self.conn.execute(
                "INSERT INTO users(email,password_hash) VALUES (%s,%s)",
                (email, password_hash),
            )
            self.conn.commit()
        except UniqueViolation as exc:
            self.conn.rollback()
            raise DuplicateUser(f"user already exists: {email}") from exc
        return self.get_user(email)

    def get_user(self, email: str) -> User:
        row = self.conn.execute(
            "SELECT id,email,password_hash,active FROM users WHERE lower(email)=lower(%s)",
            (email,),
        ).fetchone()
        if row is None:
            raise UserNotFound(f"user not found: {email}")
        return self._user(row)

    def list_users(self) -> list[User]:
        rows = self.conn.execute(
            "SELECT id,email,password_hash,active FROM users ORDER BY lower(email)"
        ).fetchall()
        return [self._user(row) for row in rows]

    def set_user_active(self, email: str, active: bool) -> User:
        cursor = self.conn.execute(
            "UPDATE users SET active=%s WHERE lower(email)=lower(%s)",
            (active, email),
        )
        if cursor.rowcount == 0:
            self.conn.rollback()
            raise UserNotFound(f"user not found: {email}")
        self.conn.commit()
        return self.get_user(email)

    def set_user_password(self, email: str, password_hash: str) -> User:
        cursor = self.conn.execute(
            "UPDATE users SET password_hash=%s WHERE lower(email)=lower(%s)",
            (password_hash, email),
        )
        if cursor.rowcount == 0:
            self.conn.rollback()
            raise UserNotFound(f"user not found: {email}")
        self.conn.commit()
        return self.get_user(email)
