import "./style.css";
import "./legend.css";
import { ApiError, loadWorkspace, saveWorkspace } from "./api";
import {
  REASONS, STATUSES, connectionCounts, encounterId, encountersForTopic,
  encountersFromContext, topicById, uniqueTopicId,
  type Encounter, type EncounterReason, type TopicStatus, type WorkspaceData,
} from "./model";
import { sampleWorkspace } from "./storage";

type View = "topics" | "detail" | "discover" | "map";
type EncounterMode = "incoming" | "outgoing" | "edit";
let data: WorkspaceData = { topics: [], encounters: [] };
let saved: WorkspaceData = structuredClone(data);
let selected: string | null = null;
let view: View = "topics";
let query = "";
let loadError: Error | null = null;

const app = document.querySelector<HTMLDivElement>("#app")!;
const esc = (s: string) => s.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const cap = (s: string) => s[0].toUpperCase() + s.slice(1);
const reasonLabel = (r: string) => r === "need" ? "Need to learn" : r === "revisit" ? "Review" : "Curious";
const topic = () => selected ? topicById(data, selected) : undefined;
const safeUrl = (value: string) => { try { const u = new URL(value); return ["http:", "https:"].includes(u.protocol) ? u.href : null; } catch { return null; } };

app.innerHTML = `<div class="app-shell">
<header><div class="brand">◆ <strong>Learning Links</strong></div><nav>${(["topics","detail","discover","map"] as View[]).map(v => `<button data-view="${v}">${v === "detail" ? "Topic" : cap(v)}</button>`).join("")}</nav><button id="add-topic" class="primary">+ Topic</button></header>
<div class="workspace"><aside><input id="search" type="search" placeholder="Search topics"><div id="topic-list"></div><footer><button id="load-sample">Load example</button><span id="topic-count"></span></footer></aside><main id="main"></main></div>
<p id="message" role="status"></p></div>
<dialog id="topic-dialog"><form id="topic-form"><div class="dialog-head"><h2 id="topic-title">Add topic</h2><button type="button" data-close="topic-dialog">×</button></div><input id="topic-id" type="hidden"><label>Name<input id="topic-name" required maxlength="100"></label><label>Status<select id="topic-status">${STATUSES.map(s => `<option value="${s}">${cap(s)}</option>`).join("")}</select></label><label>Reference URL <small>optional</small><input id="topic-url" type="url" placeholder="https://…"></label><div class="actions"><button type="button" data-close="topic-dialog">Cancel</button><button class="primary">Save</button></div></form></dialog>
<dialog id="encounter-dialog"><form id="encounter-form"><div class="dialog-head"><h2 id="encounter-title">Flag topic</h2><button type="button" data-close="encounter-dialog">×</button></div><input id="encounter-id" type="hidden"><input id="encounter-fixed" type="hidden"><input id="encounter-mode" type="hidden"><p id="encounter-help"></p><label id="other-label">Topic<select id="encounter-other"></select></label><label>Why?<select id="encounter-reason">${REASONS.map(r => `<option value="${r}">${reasonLabel(r)}</option>`).join("")}</select></label><label>Note <small>optional</small><textarea id="encounter-note" rows="3" maxlength="300"></textarea></label><p id="encounter-preview"></p><div class="actions"><button type="button" data-close="encounter-dialog">Cancel</button><button class="primary">Save encounter</button></div></form></dialog>`;

const $ = <T extends Element>(id: string) => document.getElementById(id) as unknown as T;
const main = $<HTMLElement>("main"), list = $<HTMLElement>("topic-list"), message = $<HTMLElement>("message");
const topicDialog = $<HTMLDialogElement>("topic-dialog"), encounterDialog = $<HTMLDialogElement>("encounter-dialog");
const topicId = $<HTMLInputElement>("topic-id"), topicName = $<HTMLInputElement>("topic-name"), topicStatus = $<HTMLSelectElement>("topic-status"), topicUrl = $<HTMLInputElement>("topic-url");
const encounterEditId = $<HTMLInputElement>("encounter-id"), encounterFixed = $<HTMLInputElement>("encounter-fixed"), encounterMode = $<HTMLInputElement>("encounter-mode"), encounterOther = $<HTMLSelectElement>("encounter-other"), encounterReason = $<HTMLSelectElement>("encounter-reason"), encounterNote = $<HTMLTextAreaElement>("encounter-note");

function selectTopic(id: string, next?: View) { if (!topicById(data,id)) return; selected = id; if (next) view = next; render(); }
function status(topicStatus: string) { return `<span class="status"><i class="dot ${esc(topicStatus)}"></i>${esc(topicStatus)}</span>`; }
function reasonLegend(sample: "dot" | "line") { return `<div class="legend reason-legend" aria-label="Encounter reason legend"><span class="legend-title">Reason</span>${REASONS.map(r => `<span class="legend-item"><i class="legend-${sample} ${esc(r)}"></i>${reasonLabel(r)}</span>`).join("")}</div>`; }
function statusLegend() { return `<div class="legend status-legend" aria-label="Topic status legend"><span class="legend-title">Topic status</span>${STATUSES.map(s => `<span class="legend-item"><i class="dot ${esc(s)}"></i>${cap(s)}</span>`).join("")}</div>`; }
function renderSidebar() {
  const counts = connectionCounts(data), q = query.trim().toLowerCase();
  const topics = [...data.topics].filter(t => t.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));
  $("topic-count").textContent = `${data.topics.length} topics`;
  list.innerHTML = topics.length ? topics.map(t => `<button class="topic-row${t.id===selected?" active":""}" data-topic="${esc(t.id)}"><i class="dot ${esc(t.status)}"></i><span>${esc(t.name)}</span><small>${counts.get(t.id)?.cameUpIn || ""}</small></button>`).join("") : `<p class="empty">${q?"No matches":"No topics yet"}.</p>`;
}
function card(id: string) { const t=topicById(data,id); if(!t)return""; const c=connectionCounts(data).get(id)!; return `<button class="topic-card" data-open="${esc(id)}">${status(t.status)}<strong>${esc(t.name)}</strong><p>${c.cameUpIn} contexts · led me to ${c.flagged}</p></button>`; }
function topicsView() { return data.topics.length ? `<section><div class="heading"><span>LIBRARY</span><h1>Topics</h1><p>Open a topic to see where it surfaced and what it led me to.</p></div>${statusLegend()}<div class="cards">${[...data.topics].sort((a,b)=>a.name.localeCompare(b.name)).map(t=>card(t.id)).join("")}</div></section>` : `<div class="empty-state"><h1>Capture what comes up while you learn.</h1><p>Add topics, then flag ideas whenever they surface in a study context.</p><button class="primary" data-new>+ Add your first topic</button></div>`; }
function encounterRow(e: Encounter, otherId: string) { const other=topicById(data,otherId); if(!other)return""; return `<div class="encounter-row"><button data-topic="${esc(other.id)}"><strong>${esc(other.name)}</strong><span class="reason ${esc(e.reason)}">${reasonLabel(e.reason)}</span>${e.note?`<small>${esc(e.note)}</small>`:""}</button><div><button data-edit-encounter="${esc(e.id)}">✎</button><button data-remove-encounter="${esc(e.id)}">×</button></div></div>`; }
function detailView() { const t=topic(); if(!t)return `<div class="empty-state"><h1>Choose a topic</h1></div>`; const incoming=encountersForTopic(data,t.id), ledMeTo=encountersFromContext(data,t.id), ref=safeUrl(t.url); return `<section><div class="hero"><div><span>TOPIC</span><h1>${esc(t.name)}</h1><p>${status(t.status)}${ref?` <a href="${esc(ref)}" target="_blank" rel="noopener">Reference ↗</a>`:""}</p></div><div><button data-edit-topic="${esc(t.id)}">Edit</button><button class="danger" data-delete-topic="${esc(t.id)}">Delete</button></div></div><div class="columns"><article><div class="section-head"><div><h2>Came up in ${incoming.length} ${incoming.length===1?"place":"places"}</h2><p>Contexts where you flagged ${esc(t.name)}.</p></div><button data-add-encounter="incoming">＋</button></div>${incoming.length?incoming.map(e=>encounterRow(e,e.context)).join(""):`<p class="empty">This topic has not resurfaced yet.</p>`}</article><article><div class="section-head"><div><h2>Led me to</h2><p>Things I wanted to learn, review, or explore.</p></div><button data-add-encounter="outgoing">＋</button></div>${ledMeTo.length?ledMeTo.map(e=>encounterRow(e,e.topic)).join(""):`<p class="empty">Nothing here yet.</p>`}</article></div></section>`; }
function matrix() { const rows=data.topics.filter(t=>encountersForTopic(data,t.id).length).sort((a,b)=>encountersForTopic(data,b.id).length-encountersForTopic(data,a.id).length||a.name.localeCompare(b.name)); const cols=data.topics.filter(t=>encountersFromContext(data,t.id).length).sort((a,b)=>a.name.localeCompare(b.name)); if(!rows.length||!cols.length)return`<p class="empty">Add encounters to build the matrix.</p>`; return `<div class="matrix-wrap"><table><thead><tr><th>Flagged topic ↓<br>Study context →</th>${cols.map(c=>`<th><button data-topic="${esc(c.id)}">${esc(c.name)}</button></th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr><th><button data-topic="${esc(r.id)}">${esc(r.name)}</button><small>${encountersForTopic(data,r.id).length}</small></th>${cols.map(c=>{const e=data.encounters.find(x=>x.context===c.id&&x.topic===r.id);return e?`<td><button class="matrix-dot ${esc(e.reason)}" data-open="${esc(r.id)}" title="${esc(c.name)} → ${esc(r.name)}: ${reasonLabel(e.reason)}"></button></td>`:`<td></td>`}).join("")}</tr>`).join("")}</tbody></table></div>`; }
function discoverView() { const counts=connectionCounts(data); const recurring=data.topics.map(t=>({t,count:counts.get(t.id)?.cameUpIn||0})).filter(x=>x.count>1).sort((a,b)=>b.count-a.count||a.t.name.localeCompare(b.t.name)); return `<section><div class="heading"><span>PATTERNS</span><h1>Discover</h1><p>Recurring topics rise to the top. The matrix shows exactly where they surfaced.</p></div><h2>Recurring topics</h2><div class="discover">${recurring.length?recurring.map(({t,count})=>`<button data-open="${esc(t.id)}"><b>${count}</b><strong>${esc(t.name)}</strong><small>${encountersForTopic(data,t.id).map(e=>topicById(data,e.context)?.name).filter(Boolean).slice(0,4).map(x=>esc(x as string)).join(" · ")}</small></button>`).join(""):`<p class="empty">No topic has resurfaced in more than one context yet.</p>`}</div><h2>Context matrix</h2><p class="hint">Rows are flagged topics; columns are study contexts.</p>${reasonLegend("dot")}${matrix()}</section>`; }
function egoNode(id:string,x:number,y:number,center=false){const t=topicById(data,id);if(!t)return"";return `<g class="ego-node${center?" center":""}" data-map-topic="${esc(id)}" tabindex="0" transform="translate(${x} ${y})"><rect width="${center?250:220}" height="58" rx="8"/><circle cx="16" cy="18" r="5" class="ego-status ${esc(t.status)}"/><text x="28" y="22">${esc(t.name.length>27?t.name.slice(0,26)+"…":t.name)}</text><text class="sub" x="16" y="43">${esc(t.status)}</text></g>`;}
function mapView(){const t=topic();if(!t)return`<div class="empty-state"><h1>Choose a topic</h1></div>`;const incoming=encountersForTopic(data,t.id),ledMeTo=encountersFromContext(data,t.id),max=Math.max(incoming.length,ledMeTo.length,1),h=Math.max(460,150+(max-1)*86),cy=h/2-29,y=(i:number,n:number)=>n<=1?cy:h/2-Math.min(h-120,(n-1)*86)/2+(i*Math.min(h-120,(n-1)*86))/(n-1)-29;let edges="",nodes=egoNode(t.id,355,cy,true);incoming.forEach((e,i)=>{const yy=y(i,incoming.length);edges+=`<path class="edge ${e.reason}" d="M250 ${yy+29} C300 ${yy+29},300 ${cy+29},355 ${cy+29}"/>`;nodes+=egoNode(e.context,30,yy)});ledMeTo.forEach((e,i)=>{const yy=y(i,ledMeTo.length);edges+=`<path class="edge ${e.reason}" d="M605 ${cy+29} C655 ${cy+29},655 ${yy+29},710 ${yy+29}"/>`;nodes+=egoNode(e.topic,710,yy)});return`<section><div class="heading"><span>LOCAL MAP</span><h1>${esc(t.name)}</h1><p>Only immediate encounters are shown. Select a neighbor to recenter.</p></div><div class="map-legends">${reasonLegend("line")}${statusLegend()}</div><div class="map-labels"><span>CAME UP IN</span><span>SELECTED</span><span>LED ME TO</span></div><div class="map-wrap"><svg viewBox="0 0 960 ${h}"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8z"/></marker></defs>${edges}${nodes}</svg></div></section>`;}

function render(){ if(selected&&!topicById(data,selected))selected=null; renderSidebar(); document.querySelectorAll<HTMLButtonElement>("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view)); if(loadError){main.innerHTML=`<div class="empty-state"><h1>${loadError instanceof ApiError&&loadError.status===401?"Sign in required":"Could not load workspace"}</h1><button class="primary" id="retry">Try again</button></div>`;return;} main.innerHTML=view==="topics"?topicsView():view==="detail"?detailView():view==="discover"?discoverView():mapView(); }
async function persist(text:string){const before=structuredClone(saved);try{await saveWorkspace(data);saved=structuredClone(data);message.textContent=text;render()}catch(e){data=before;saved=structuredClone(before);message.textContent=`Save failed: ${e instanceof Error?e.message:String(e)}`;render()}}
function openTopic(id?:string){const t=id?topicById(data,id):undefined;$("topic-title").textContent=t?"Edit topic":"Add topic";topicId.value=t?.id||"";topicName.value=t?.name||"";topicStatus.value=t?.status||"planned";topicUrl.value=t?.url||"";topicDialog.showModal();topicName.focus()}
function encounterPreview(){const fixed=topicById(data,encounterFixed.value),other=topicById(data,encounterOther.value),mode=encounterMode.value as EncounterMode;let context=fixed,target=other;if(mode==="incoming"){context=other;target=fixed}else if(mode==="edit"){const e=data.encounters.find(x=>x.id===encounterEditId.value);context=e?topicById(data,e.context):undefined;target=e?topicById(data,e.topic):undefined}$("encounter-preview").textContent=context&&target?`While studying ${context.name}, you flagged ${target.name} · ${reasonLabel(encounterReason.value)}.`:""}
function openEncounter(mode:"incoming"|"outgoing"){const t=topic();if(!t)return;const others=data.topics.filter(x=>x.id!==t.id).sort((a,b)=>a.name.localeCompare(b.name));if(!others.length){message.textContent="Add another topic first.";return}encounterEditId.value="";encounterFixed.value=t.id;encounterMode.value=mode;encounterReason.value="need";encounterNote.value="";encounterOther.disabled=false;encounterOther.innerHTML=others.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");$("encounter-title").textContent=mode==="outgoing"?"Flag a topic":"Add a study context";$("encounter-help").textContent=mode==="outgoing"?`What came up while studying ${t.name}?`:`Where did ${t.name} come up?`;encounterPreview();encounterDialog.showModal()}
function editEncounter(id:string){const e=data.encounters.find(x=>x.id===id);if(!e)return;const c=topicById(data,e.context),t=topicById(data,e.topic);if(!c||!t)return;encounterEditId.value=id;encounterFixed.value=c.id;encounterMode.value="edit";encounterReason.value=e.reason;encounterNote.value=e.note;encounterOther.disabled=true;encounterOther.innerHTML=`<option value="${esc(t.id)}">${esc(t.name)}</option>`;$("encounter-title").textContent="Edit encounter";$("encounter-help").textContent=`${c.name} → ${t.name}`;encounterPreview();encounterDialog.showModal()}

$<HTMLInputElement>("search").addEventListener("input",e=>{query=(e.target as HTMLInputElement).value;renderSidebar()});
$("topic-form").addEventListener("submit",async e=>{e.preventDefault();const id=topicId.value,name=topicName.value.trim();if(!name)return;if(data.topics.some(t=>t.id!==id&&t.name.toLowerCase()===name.toLowerCase())){message.textContent="A topic with that name already exists.";return}if(id){const t=topicById(data,id)!;Object.assign(t,{name,status:topicStatus.value as TopicStatus,url:topicUrl.value.trim()});selected=id}else{const t={id:uniqueTopicId(data,name),name,status:topicStatus.value as TopicStatus,url:topicUrl.value.trim()};data.topics.push(t);selected=t.id;view="detail"}topicDialog.close();await persist(id?`Updated “${name}”.`:`Added “${name}”.`)});
$("encounter-form").addEventListener("submit",async e=>{e.preventDefault();const mode=encounterMode.value as EncounterMode,reason=encounterReason.value as EncounterReason,note=encounterNote.value.trim();if(mode==="edit"){const old=data.encounters.find(x=>x.id===encounterEditId.value);if(old){old.reason=reason;old.note=note}encounterDialog.close();await persist("Encounter updated.");return}const fixed=encounterFixed.value,other=encounterOther.value,context=mode==="incoming"?other:fixed,target=mode==="incoming"?fixed:other,old=data.encounters.find(x=>x.context===context&&x.topic===target);if(old){old.reason=reason;old.note=note}else data.encounters.push({id:encounterId(context,target),context,topic:target,reason,note});encounterDialog.close();await persist(old?"Encounter updated.":"Encounter added.")});
encounterOther.addEventListener("change",encounterPreview);encounterReason.addEventListener("change",encounterPreview);
document.addEventListener("click",async e=>{const el=e.target as Element,map=el.closest<SVGGElement>("[data-map-topic]");if(map){selectTopic(map.dataset.mapTopic!);return}const b=el.closest<HTMLButtonElement>("button");if(!b)return;if(b.dataset.view){view=b.dataset.view as View;render()}else if(b.dataset.close)$<HTMLDialogElement>(b.dataset.close).close();else if(b.id==="add-topic"||b.dataset.new!==undefined)openTopic();else if(b.id==="retry")await start();else if(b.dataset.open)selectTopic(b.dataset.open,"detail");else if(b.dataset.topic)selectTopic(b.dataset.topic,"detail");else if(b.dataset.editTopic)openTopic(b.dataset.editTopic);else if(b.dataset.addEncounter)openEncounter(b.dataset.addEncounter as "incoming"|"outgoing");else if(b.dataset.editEncounter)editEncounter(b.dataset.editEncounter);else if(b.dataset.removeEncounter){const item=data.encounters.find(x=>x.id===b.dataset.removeEncounter);if(item&&confirm("Remove this encounter?")){data.encounters=data.encounters.filter(x=>x.id!==item.id);await persist("Encounter removed.")}}else if(b.dataset.deleteTopic){const t=topicById(data,b.dataset.deleteTopic);if(t&&confirm(`Delete “${t.name}” and its encounters?`)){data.topics=data.topics.filter(x=>x.id!==t.id);data.encounters=data.encounters.filter(x=>x.context!==t.id&&x.topic!==t.id);selected=data.topics[0]?.id||null;view=selected?"detail":"topics";await persist(`Deleted “${t.name}”.`)}}else if(b.id==="load-sample"&&confirm("Replace the current workspace with the example?")){data=sampleWorkspace();selected="differential-equations";view="discover";await persist("Example loaded.")}});
document.addEventListener("keydown",e=>{const el=e.target as Element;if((e.key==="Enter"||e.key===" ")&&el.matches("[data-map-topic]")){e.preventDefault();selectTopic((el as HTMLElement).dataset.mapTopic!)}});
async function start(){try{data=await loadWorkspace();saved=structuredClone(data);loadError=null;selected=data.topics[0]?.id||null;message.textContent="Connected"}catch(e){loadError=e instanceof Error?e:new Error(String(e));message.textContent=`API unavailable: ${loadError.message}`}render()}
void start();
